/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // TODO: 16.04.21 implement tests 
}
